kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: prints.stable.marvfadev.me
spec:
  group: stable.marvfadev.me
  scope: Cluster
  names:
    plural: prints
    singular: print
    shortNames:
      - prt
    kind: Print
    listKind: PrintList
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                path:
                  type: string
                schedule:
                  type: string
                filename:
                  type: string

