apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.name }}
  namespace: {{ .Values.name }}
  labels:
    app: "{{ .Values.name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"
    spec:
      containers:
        - image: "{{ .Values.deployment.image }}:{{ .Values.deployment.tag }}"
          name: {{ .Values.name }}
          volumeMounts:
          - mountPath: /usr/share/prints
            name: prints-volume
          # ports:
          #   - containerPort: 8080
          #     protocol: TCP
      volumes:
      - name: prints-volume
        hostPath:
          #Directory on the host
          path: /prints
      serviceAccountName: {{ .Values.name }}
