apiVersion: batch/v1
kind: CronJob
metadata:
  name: ts-operator
  labels:
    app: ts-operator
  namespace: ts-operator
spec:
            # ┌───────────── minute (0 - 59)
            # │ ┌───────────── hour (0 - 23)
            # │ │ ┌───────────── day of the month (1 - 31)
            # │ │ │ ┌───────────── month (1 - 12)
            # │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
            # │ │ │ │ │                                   7 is also Sunday on some systems)
            # │ │ │ │ │
            # │ │ │ │ │
            # * * * * *
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: ts-operator
        spec:
          containers:
          - image: luisbodev/js-operator:latest
            name: ts-operator
          restartPolicy: OnFailure
          serviceAccount: ts-operator-sa
